---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacman2 
  namespace: pacman2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pacman2
  namespace: pacman2 
subjects:
- kind: ServiceAccount 
  name: pacman2
  namespace: pacman2
roleRef:
  kind: ClusterRole
  name: pacman2
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pacman2
rules:
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secret
  namespace: pacman2
type: Opaque 
data:
  database-admin-password: Y2x5ZGU=
  database-name: cGFjbWFu
  database-password: cGlua3k=
  database-user: Ymxpbmt5
  keyfile-value: cjNkaDR0Cg==
